- name: Configure homelab server
  hosts: all
  become: true

  roles:
    - role: base
      tags: base

    - role: users_ssh
      tags: users_ssh

    - role: storage
      tags: storage

    - role: docker
      tags: docker

    - role: docker_networks
      tags: docker_networks

    - role: firewall
      tags: firewall

    - role: wireguard
      tags: wireguard

    - role: homelab
      tags: homelab