services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped

    volumes:
      - /mnt/data/docker/uptime-kuma:/app/data

    networks:
      - proxy

networks:
  proxy:
    external: true
