services:
  portainer:
    image: portainer/portainer-ee:2.39.6
    container_name: portainer
    restart: unless-stopped

    environment:
      TRUSTED_ORIGINS: "portainer.${HOMELAB_DOMAIN}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/docker/portainer:/data

    networks:
      - proxy

networks:
  proxy:
    external: true
