homelab_domain: afcasco.dev
server_hostname: gizmo
server_timezone: Etc/UTC

base_packages:
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - jq
  - nano
  - rsync
  - wget
  - parted
  - e2fsprogs
  - acl

bootstrap_user: ubuntu
admin_user: afcasco
admin_user_shell: /bin/bash

admin_user_groups:
  - sudo
  - users

admin_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaeGefakiewZ5iEqYvQ+M40HA9ZFhFkPSBbH9iXoqXZTkhCRjuOeJXSsVs4PB3GSlxhGVEynieKSn6Lg374bDjosRwwL+Gl2ra9oEnMFTHYFUIBTOJpRUL4PdN2IORFnFGzxeA1nuVbSUi5S450AhFgn3apwov6deFMkJEAxDRdGLysPPk2AmutK+UmDxIJ6yd3mLX01n4sYANeBONwkc/w5pmQCFkiluLec6C/cqc6RjIUBNzwdA7jzKfP8LeHei1a5dmuElh1xoKRKj4wB4ohI9nv6EQYODs8Ea5XODWICw+i1GIK6iwvvga9/dQFzMx/IU22Ojo0lfNZ1mV2LM3 ssh-key-2026-07-11"

wireguard_interface: wg0
wireguard_port: 51820
wireguard_network: 10.66.66.0/24
wireguard_server_address: 10.66.66.1/24

wireguard_peers:
  - name: pr819
    public_key: "{{ vault_wireguard_pr819_public_key }}"
    address: 10.66.66.2/32

data_mount_path: /mnt/data
data_filesystem_type: ext4
data_filesystem_label: data-new
data_mount_options: defaults,nofail

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_users:
  - afcasco

managed_stacks:
  - caddy
  - portainer
  - uptime-kuma
  - monitoring
  - authentik

enabled_stacks:
  - caddy
  - portainer
  - uptime-kuma
  - monitoring
  - authentik

caddy_bind_ip: 10.0.0.137

grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_url: "https://grafana.{{ homelab_domain }}"
authentik_url: "https://auth.{{ homelab_domain }}"
grafana_oidc_client_secret: "{{ vault_grafana_oidc_client_secret }}"
grafana_oidc_client_id: grafana

portainer_admin_user: afcasco
portainer_admin_password: "{{ vault_portainer_admin_password }}"
portainer_url: "https://portainer.{{ homelab_domain }}"
portainer_oidc_client_id: portainer
portainer_oidc_client_secret: "{{ vault_portainer_oidc_client_secret }}"

authentik_primary_user: afcasco
authentik_primary_user_name: "Alex"
authentik_primary_user_email: "afcasco@gmail.com"
authentik_primary_user_password: "{{ vault_authentik_primary_user_password }}"
authentik_pg_db: authentik
authentik_pg_user: authentik
authentik_pg_pass: "{{ vault_authentik_pg_pass }}"
authentik_secret_key: "{{ vault_authentik_secret_key }}"

persistent_directories:
  - path: /mnt/data/docker/caddy/data
    owner: 0
    group: 0
    mode: "0755"

  - path: /mnt/data/docker/caddy/config
    owner: 0
    group: 0
    mode: "0755"

  - path: /mnt/data/docker/portainer
    owner: 1002
    group: 1002
    mode: "0775"

  - path: /mnt/data/docker/uptime-kuma
    owner: 0
    group: 0
    mode: "0755"

  - path: /mnt/data/docker/monitoring/prometheus
    owner: 65534
    group: 65534
    mode: "0755"

  - path: /mnt/data/docker/monitoring/grafana
    owner: 472
    group: 472
    mode: "0755"

  - path: /mnt/data/docker/monitoring/loki
    owner: 10001
    group: 10001
    mode: "0755"

  - path: /mnt/data/docker/monitoring/alertmanager
    owner: 0
    group: 0
    mode: "0755"

  - path: /mnt/data/docker/authentik/postgresql
    owner: 70
    group: 70
    mode: "0700"

  - path: /mnt/data/docker/authentik/data
    owner: 1000
    group: 1000
    mode: "0755"

  - path: /mnt/data/docker/authentik/certs
    owner: 1000
    group: 1000
    mode: "0755"