- name: Ensure Authentik blueprint directory exists
  ansible.builtin.file:
    path: /opt/stacks/authentik/blueprints
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"

- name: Ensure Authentik blueprint directory owner permissions
  ansible.posix.acl:
    path: /opt/stacks/authentik/blueprints
    etype: user
    permissions: "rwx"
    state: present

- name: Allow Authentik worker to access blueprint directory
  ansible.posix.acl:
    path: /opt/stacks/authentik/blueprints
    entity: "1000"
    etype: user
    permissions: "rx"
    state: present

- name: Deny group access to blueprint directory
  ansible.posix.acl:
    path: /opt/stacks/authentik/blueprints
    etype: group
    permissions: "---"
    state: present

- name: Deny other access to blueprint directory
  ansible.posix.acl:
    path: /opt/stacks/authentik/blueprints
    etype: other
    permissions: "---"
    state: present