services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped

    environment:
      SECURITY_ENABLELOGIN: ${SECURITY_ENABLELOGIN}
      SECURITY_INITIALLOGIN_USERNAME: ${STIRLING_ADMIN_USER}
      SECURITY_INITIALLOGIN_PASSWORD: ${STIRLING_ADMIN_PASSWORD}
      SECURITY_LOGINMETHOD: ${SECURITY_LOGINMETHOD}

      SECURITY_OAUTH2_ENABLED: ${SECURITY_OAUTH2_ENABLED}
      SECURITY_OAUTH2_ISSUER: ${SECURITY_OAUTH2_ISSUER}
      SECURITY_OAUTH2_CLIENTID: ${SECURITY_OAUTH2_CLIENTID}
      SECURITY_OAUTH2_CLIENTSECRET: ${SECURITY_OAUTH2_CLIENTSECRET}
      SECURITY_OAUTH2_SCOPES: ${SECURITY_OAUTH2_SCOPES}
      SECURITY_OAUTH2_USEASUSERNAME: ${SECURITY_OAUTH2_USEASUSERNAME}
      SECURITY_OAUTH2_AUTOCREATEUSER: ${SECURITY_OAUTH2_AUTOCREATEUSER}
      SECURITY_OAUTH2_BLOCKREGISTRATION: ${SECURITY_OAUTH2_BLOCKREGISTRATION}
      SECURITY_OAUTH2_PROVIDER: ${SECURITY_OAUTH2_PROVIDER}

      SYSTEM_BACKENDURL: ${SYSTEM_BACKENDURL}
      SYSTEM_FRONTENDURL: ${SYSTEM_FRONTENDURL}

      SYSTEM_DEFAULTLOCALE: es-ES
      DISABLE_ADDITIONAL_FEATURES: "false"

    volumes:
      - /mnt/data/docker/stirling-pdf/configs:/configs
      - /mnt/data/docker/stirling-pdf/logs:/logs
      - /mnt/data/docker/stirling-pdf/pipeline:/pipeline
      - /mnt/data/docker/stirling-pdf/customFiles:/customFiles
      - /mnt/data/docker/stirling-pdf/tessdata:/usr/share/tessdata

    networks:
      - proxy

networks:
  proxy:
    external: true
